version: 2
updates:
  # console
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update:"
    target-branch: "master"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "strip-json-comments"
        update-types: ["version-update:semver-major"]
      - dependency-name: "node-fetch"
        update-types: ["version-update:semver-major"]
        
  # actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update(action):"
    target-branch: "master"
    labels:
      - "dependencies"
      - "github_actions"

  # webui
  - package-ecosystem: npm
    directory: "/webui"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update:"
    target-branch: "master"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
    allow:
      - dependency-type: "direct"
